
export const DISCOVERY_BP3L = 'DISCOVERY_BP3L'
export const DISCOVERY_BP3L_AGAIN = 'DISCOVERY_BP3L_AGAIN'
export const STOP_DISCOVERY_BP3L = 'STOP_DISCOVERY_BP3L'
export const CONNECT_BP3L = 'CONNECT_BP3L'
export const CONNECT_BP3L_AGAIN = 'CONNECT_BP3L_AGAIN'
export const DIS_CONNECT_BP3L = 'DIS_CONNECT_BP3L'
export const START_MEASURE = 'START_MEASURE'
export const STOP_MEASURE = 'STOP_MEASURE'
